portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/create/', views.customer_new, name='customer_new'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    path('portfolio_pdf/<int:pk>/pdf/', views.portfolio_pdf, name='portfolio_pdf'),


]
urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <html>
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,shrink-to-fit=yes">

        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">


    </head>


    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div class="table-responsive" >
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>

                    </td>
                    <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a>
                    </td>
                    <td><a href="{% url 'portfolio:portfolio_pdf' pk=customer.pk %}"
                           class="btn btn-primary">SEND PDF</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">


    </div>

        </div>
  </body>
    <a href="{% url 'portfolio:customer_new' %}" class="row"><span
                    class="btn btn-primary">Add Customer</span></a>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    </html>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <html>
    <head>
          <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,shrink-to-fit=yes">

        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Investment Information</h2>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Customer</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Acquired Value</th>
                    <th>Acquired Date</th>
                    <th>Recent Value</th>
                    <th>Recent Date</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
                <tr>
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date  }}</td>
                    <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

            {% endfor %}
            </tbody>
        </table>


    </div>
     <div class="row">
                        <a href="{% url 'portfolio:investment_new' %}" class="row"><span class="btn btn-primary">Add Investment</span></a>
     </div>
  </body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    </html>
{% endblock %}

portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% load humanize %}
{% load mathfilters %}
{% block content %}

    <html>
            <head>
                <meta charset="UTF-8">
                <title>Eagle Financial</title>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

            </head>

            <body>
                     <div class="container">
                                <div class="responsive">
                                    <div class="col-md-10 col-md-offset-1">
                                        <div class="panel panel-primary">
                                            <div class="panel-heading">Welcome!</div>
                                            <div class="panel-body">
                                                Eagle Financial Services, your Midwest Financial Services Partner.
                                            </div>
                                        </div>
                                    </div>
                               </div>

                        </div>
<div class="row">
    <h1 style="padding-left: 15Px">Customer Portfolio</h1>
</div>
<div class="row-responsive">
    <h2 style="padding-left: 15Px">Overall Portfolio Performance</h2>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info-responsive">
            <th>Portfolio Initial Investments </th>
            <th>Portfolio Current Investments</th>
            <th>Grand Total Results</th>
             <th>Converted Value From EUR to USD</th>
        </tr>
        </thead>
        <tbody>

            <tr>
                <td>{{ sum_of_initial_stock_value|add:sum_initial_investment|intcomma }}</td>
                <td>{{ sum_current_stocks_value|add:sum_current_investment|intcomma}}</td>
                <td>{{grand_total_results|intcomma}}</td>
                <td>{{grand_total_results|mul:result|intcomma}}</td>
            </tr>

        </tbody>
    </table>
</div>
</div>
<div>
<div class="row">
    <h2 style="padding-left: 15Px">Stocks Information</h2>
</div>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Initial Stock Price</th>
            <th>Initial Stock Value</th>
            <th>Current Stock price</th>
            <th>Current Stock value</th>
            <th>Results</th>

        </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
            <tr>
                <td>{{ stock.customer }}</td>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.name }}</td>
                <td>{{ stock.shares|intcomma }}</td>
                <td>{{ stock.purchase_price|intcomma }}</td>
                <td>{{ stock.initial_stock_value|intcomma}}</td>
                <td> {{ stock.current_stock_price|intcomma}}</td>
                <td>{{ stock.current_stock_value|intcomma}}</td>
                <td>{{stock.current_stock_value|sub:stock.initial_stock_value|intcomma }}</td>



            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

 <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Stocks</th>
            <th>Total of current Stocks</th>
            <th>Results</th>
            <th>Converted value from Euro To USD</th>
        </tr>
        </thead>
        <tbody>

            <tr>
                <td>{{ sum_of_initial_stock_value|intcomma }}</td>
                <td>{{ sum_current_stocks_value|intcomma }}</td>
                <td>{{ sum_current_stocks_value|sub:sum_of_initial_stock_value|intcomma }}</td>
                <td>{{stockresult|mul:result|intcomma}}</td>

            </tr>

        </tbody>
    </table>
</div>
</div>
            <div class="row">
        <h2 style="padding-left: 15Px">Investment Information</h2>
            </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Category</th>
            <th>Description</th>
            <th>Acquired value</th>
            <th>Acquired Date</th>
            <th>Recent Value</th>
            <th>Recent Date</th>
            <th>Results</th>
        </tr>
        </thead>
        <tbody>
        {% for investment in investments %}
            <tr>
                <td>{{ investment.customer }}</td>
                <td>{{ investment.category }}</td>
                <td>{{ investment.description }}</td>
                <td>{{ investment.acquired_value|intcomma }}</td>
                <td>{{ investment.acquired_date }}</td>
                <td>{{ investment.recent_value|intcomma }}</td>
                <td>{{ investment.recent_date }}</td>
                <td>{{investment.recent_value|sub:investment.acquired_value|intcomma }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Investments</th>
            <th>Total of current Investments</th>
            <th>Results</th>
            <th>Converted value from Euro To USD</th>
        </tr>
        </thead>
        <tbody>

            <tr>
                <td>{{ sum_initial_investment|intcomma }}</td>
                <td>{{ sum_current_investment|intcomma }}</td>
                <td>{{ sum_current_investment|sub:sum_initial_investment|intcomma }}</td>
                <td>{{ investmentresult|mul:result|intcomma}}</td>


            </tr>

        </tbody>
    </table>
</div>
     <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



{% endblock %}